services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/sport_school_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres_password"
    depends_on:
      - postgres
    networks:
      - app_net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "sport_school_db"
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=100
               -c shared_buffers=512MB
               -c effective_cache_size=1536MB
               -c maintenance_work_mem=128MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=-1
               -c default_statistics_target=100
               -c huge_pages=off
               -c effective_io_concurrency=200
               -c work_mem=512MB
               -c min_wal_size=1GB
               -c max_wal_size=4GB
               -c checkpoint_timeout=2min
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sport_school_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - app_net

volumes:
  pgdata:
    driver: local

networks:
  app_net:
    driver: bridge
